//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fis_administrator.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fisEntities : DbContext
    {
        public fisEntities()
            : base("name=fisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<citys> citys { get; set; }
        public virtual DbSet<countrys> countrys { get; set; }
        public virtual DbSet<permissions> permissions { get; set; }
        public virtual DbSet<professions> professions { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<roles_permissions> roles_permissions { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<services_comments> services_comments { get; set; }
        public virtual DbSet<services_confirm> services_confirm { get; set; }
        public virtual DbSet<services_status> services_status { get; set; }
        public virtual DbSet<services_types> services_types { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<transaccions> transaccions { get; set; }
        public virtual DbSet<transactions_returns> transactions_returns { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<users_comments> users_comments { get; set; }
        public virtual DbSet<users_profile> users_profile { get; set; }
        public virtual DbSet<users_qualify> users_qualify { get; set; }
    }
}
