//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fis_administrator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles_permissions
    {
        public int id { get; set; }
        public int role_id { get; set; }
        public int user_id { get; set; }
        public int permission_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual permissions permissions { get; set; }
        public virtual roles roles { get; set; }
        public virtual users users { get; set; }
    }
}
