//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fis_administrator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class services_confirm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public services_confirm()
        {
            this.transaccions = new HashSet<transaccions>();
        }
    
        public int id { get; set; }
        public int service_id { get; set; }
        public decimal price { get; set; }
        public decimal service_time { get; set; }
        public decimal total_price { get; set; }
        public System.DateTime request_date { get; set; }
        public System.DateTime delivery_date { get; set; }
        public int service_status_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual services services { get; set; }
        public virtual services_status services_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaccions> transaccions { get; set; }
    }
}
