//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fis_administrator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaccions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transaccions()
        {
            this.transactions_returns = new HashSet<transactions_returns>();
        }
    
        public int id { get; set; }
        public int services_confirm_id { get; set; }
        public string bussines_porcentage { get; set; }
        public int mount { get; set; }
        public decimal app_mount { get; set; }
        public decimal user_mount { get; set; }
        public int user_beneficiary_id { get; set; }
        public string platform_id { get; set; }
        public string receipt { get; set; }
        public string signature { get; set; }
        public string product_type { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual services_confirm services_confirm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transactions_returns> transactions_returns { get; set; }
    }
}
