//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fis_administrator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_profile
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public int city { get; set; }
        public int country { get; set; }
        public int gender { get; set; }
        public string description { get; set; }
        public int profession { get; set; }
        public decimal phone { get; set; }
        public string address { get; set; }
        public System.Data.Entity.Spatial.DbGeography geolocalization { get; set; }
        public string image { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual citys citys { get; set; }
        public virtual countrys countrys { get; set; }
        public virtual professions professions { get; set; }
        public virtual users users { get; set; }
    }
}
